id: P009442
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137891
  title: བོད་ཀྱི་བསྟན་རྩིས་ཀུན་གསལ་བཻ་ཌཱུརྱའི་མགུལ་རྒྱན།
  author: ''
  volumes:
    70eb1d8e2c5747ca817eef08b3b88bd2:
      image_group_id: I2PD18070
      title: ''
      volume_number: 1
      total_pages: 1162
      base_file: v001.txt
